### PR TITLE
set the project structure

### PR DESCRIPTION
**Pull request by Roland-Sankara**
### What this PR does?
It sets the default project structure that the team is to follow.

### CODE REVIEW

**Comment by brianBaguma** [comment]
am learning something , this is nice work

**Comment by FREDVUNI** [comment]
This is fine. Github!!!

**Review by BelindaNabudde — APPROVED** [review]

**Review by brianBaguma — APPROVED** [review]

**Comment by Eustagoz** [comment]
So great!

**Review by BelindaNabudde — COMMENTED** [review]
we are still learning

**Pull request merged**
